### ISSUE TITLE
[DOC] How to use GPUs

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#119]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

Old docs: https://docs.qhub.dev/en/latest/source/admin_guide/gpu.html

### Steps to Resolve this Issue

.

**Comment by ericdatakelly** [comment]
@kcpevey Is the goal of this issue to make a 'how to' for the admin or the user?  And if it's for the user, are we sure we want to explain how to install libraries for using GPUs?  I think there are too many cases to cover and we should rely on external sources for that (PyTorch docs, Nvidia docs, etc.). 

The only gotcha I've found for the user so far is the one @dillonroach found about ensuring the environment has the GPU-specific library included (`pytorch-gpu` or `tensorflow-gpu`).  I just tested pytorch and tensorflow and both worked fine with the GPU server as long as the GPU-specific library was present.  I was going to suggest adding this to the FAQ because it only takes a couple of sentences to describe it.  What do you think?

**Comment by kcpevey** [comment]
In general, I find that our How-tos tend to be more admin related and our tutorials tend to be more user-focused. That said, there is still ambiguity here. 

In the end we need two different documents - `How to set up GPU instances` and `Running codes on GPUs` (a tutorial?). 

> I was going to suggest adding this to the FAQ because it only takes a couple of sentences to describe it. What do you think?

Expanding the FAQ is always appreciated in my book. Its a low effort PR that provides quick feedback to users. The full explanation can come later in the complete doc. 

We dont have any gpu-ready environments deployed with nebari, do we?

**Comment by ericdatakelly** [comment]
Thanks.  I'll add the info I mentioned above to a PR for the FAQ.  If we decide to make a user-focused tutorial/guide/how-to, I'm happy to make it or assist.

Yes, we have a single GPU option at the moment.  Not sure how long it's been there.

**Comment by kcpevey** [comment]
End user:
* Need to add information on adding the conda-store env var in the environment. 

Admin:
* request from cloud provider
* add it to the nebari-config.yml

**Comment by pt247** [comment]
@kcpevey I can't access the notion page in the description. Do I need that, or is the information in the last comment enough?

**Comment by kcpevey** [comment]
There is nothing of importance in the notion doc, I've removed it. 

>Need to add information on adding the conda-store env var in the environment.

Here is an example:

```
channels:
  - conda-forge
dependencies:
  - pytorch
  - ipykernel
variables:
  CONDA_OVERRIDE_CUDA: "12.0"
```

You have to add this env var because conda-store is building the environment on a CPU and this environment variable is telling conda-store to ignore that and build a GPU-compatible environment.

**Comment by pt247** [comment]
How about we make the following changes: 
### Change 1
Add the following to [pytorch-best-practices](https://www.nebari.dev/docs/how-tos/pytorch-best-practices).
> **Passing environment variable to conda-store build.**
> Conda provides a mechanism to override virtual package detection using an environment variable as explained in [conda docs](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-virtual.html#overriding-detected-packages).
To set environment variables, click on the GUI <-> YAML Toggel to expose the underlying config. You will see a config ending with `variables: {}`. This needs to be replaced with the variable you want to override. For example, in the example below, we override `CONDA_OVERRIDE_CUDA` to tell the conda-store to build a GPU-compatible environment instead of the default CPU-compatible one. 
> ```
> variables:
>   CONDA_OVERRIDE_CUDA: "12.0"
> ```

It should go just before 
> Add any other packages you need and click `Create` to build the environment.

### Change 2
Add a FAQ for adding environment variables in [docs/faq](https://www.nebari.dev/docs/faq)
> **How to add environment variables to my conda-store builds?** 
> Instructions to add environment variables are described in [pytorch-best-practices#passing-environment-variable-to-conda-store-build](https://www.nebari.dev/docs/how-tos/pytorch-best-practices#passing-environment-variable-to-conda-store-build). You might need this when building GPU-compatibles environments for your project.  

### Reasoning 
Users landing on the PyTorch best practices page most likely want to build GPU-enabled environments. The instructions there must include instructions on how to construct GPU-enabled environments. The FAQ can point towards the same section, making it easier for users to follow the instructions in one place. 

Do you agree? What do you think? 
cc. @kcpevey @pavithraes

**Comment by kcpevey** [comment]
I learned yesterday that only ONE environment variable is available in conda-store and that is the `CONDA_OVERRIDE_CUDA` variable. We'll need to reword this so that is more clear. 

This next section should go just BELOW `Add any other packages you need and click Create to build the environment.`

<hr>

## Building a GPU-enabled environment using `CONDA_OVERRIDE_CUDA`

Conda-store provides a mechanism to enable GPU environments via the setting of an environment variable as explained in the [conda-store docs](https://conda.store/conda-store-ui/tutorials/create-envs#set-environment-variables). 

To set this environment variable in conda-store, click on the GUI <-> YAML Toggle to expose the underlying config. You will see a config ending with variables: {}. We will replace this section with an override for `CONDA_OVERRIDE_CUDA` to tell the conda-store to build a GPU-compatible environment instead of the default CPU-compatible one.

Using this approach, we no longer need to specify both `pytorch` and `pytorch-cuda` since conda will bring in the appropriate CUDA packages for us. 

```
channels:
  - conda-forge
dependencies:
  - pytorch
variables:
  CONDA_OVERRIDE_CUDA: "12.0"
```
<hr>

For the FAQ item, 

<hr>
## How do I build GPU-enabled environments?

Conda-store will build CPU-based environments by default. However, GPU-enabled environments can be built by overriding the `CONDA_OVERRIDE_CUDA` variable in the environment YAML specification. More details on this approach are described in [pytorch-best-practices#passing-environment-variable-to-conda-store-build](https://www.nebari.dev/docs/how-tos/pytorch-best-practices#passing-environment-variable-to-conda-store-build). 

<hr>


Last, it looks like we need to update this FAQ item:
>Why doesn't my code recognize the GPU(s) on Nebari?

and reference the new FAQ section and GPU doc.

**Comment by ericdatakelly** [comment]
It would be helpful to remind the user how to check which cuda version to choose for the override variable.  They would need to start the GPU server they intend to use, open a terminal, run `nvidia-smi`, and read the cuda driver version installed for the GPU.

**Comment by kcpevey** [comment]
@ericdatakelly that's a good point. I think we just need a whole new page on GPUs. The pytorch page can just reference this new page. 

We should include a mention of starting a GPU server after login, creating GPU-based environments, and then how to check if you're currently on a GPU-enabled server and getting information about that GPU. 

Two approaches for the GPU check is 
* to use `nvidia-smi` but that is only available on GPUs
* to use pytorch to check:

```
import torch
torch.cuda.is_available()
torch.cuda.device_count()
torch.cuda.current_device()
torch.cuda.device(0)
torch.cuda.get_device_name(0)
```

Those results might look like this on a GPU:
![image](https://github.com/nebari-dev/nebari-docs/assets/15659110/75e05a46-4426-4eff-997e-7d9965a44bc4)

**Comment by ericdatakelly** [comment]
> @ericdatakelly that's a good point. I think we just need a whole new page on GPUs. The pytorch page can just reference this new page.

My two cents: I'd rather have all GPU help on one page if that makes sense in the doc structure.

> ```
> import torch
> torch.cuda.is_available()
> torch.cuda.device_count()
> torch.cuda.current_device()
> torch.cuda.device(0)
> torch.cuda.get_device_name(0)
> ```

Just to be sure we're describing the same thing, this code won't give the cuda driver version (version of cuda supporting the GPU hardware), so I wouldn't call it another approach, but I agree it is helpful info for the docs.

For the cuda version, `nvidia-smi` is the only way to get the hardware driver version (at least with NVIDIA GPUs).  `nvcc --version` provides the cuda toolkit version, but that's what conda would be installing to match the hardware driver.  You might double check with a pytorch developer to confirm though.

**Comment by kcpevey** [comment]
>Just to be sure we're describing the same thing, this code won't give the cuda driver version

that's good to know! Thanks for all the additional info on this. We'll include it in the docs.

**Comment by pt247** [comment]
**Disclaimer**: I have never worked with GPUs. I have written this content after only a day of research. So expert opinions are more than welcome. :) 

Here is the first draft - [link to netlify app](https://deploy-preview-471--nebari-docs.netlify.app/docs/how-tos/use-gpus). 

I can add more info/images around nebari specific things like conda-store env creation. But at this stage, I would appreciate it if @ericdatakelly / @kcpevey could help review GPU-specific content on the page.

**Comment by ericdatakelly** [comment]
It's looking good @pt247 !  Here are some suggestions:

Remove step 1.4: "Run nvcc --version to find the CUDA version installed on the server. You might need this in the next step."  This command is not needed.  It shows the version of the cuda toolkit (not the hardware driver), and you won't have a toolkit installed yet.  After running the conda solve in conda store, you can see which cuda toolkit is in the list of conda packages. The toolkit is really not worth mentioning actually.

Step 2.2.i.: "You might want to check Pytorch documentation to select a supported version of CUDA from our support matrix for compatibility."  I suggest giving them the appropriate options to use in the matrix.  The user might not know to choose linux and conda, for example. (or just link to the 'Pytorch best practices' page)

"Go to JupyterHub Homepage and find the newly created environment for GPUs."  Do you mean "JupyterLab Launcher" instead of "JupyterHub Homepage"?

These need to be run in individual cells or as print statements:
```python
import torch
torch.cuda.is_available()
torch.cuda.device_count()
torch.cuda.current_device()
torch.cuda.device(0)
torch.cuda.get_device_name(0)
```
This one is not helpful to me, so I wouldn't include it:
`torch.cuda.device(0)`

To make it nice for the user, how about putting them into one cell and making more informative print statements, such as:
```python
import torch

print(f"GPU available: {torch.cuda.is_available()}")
print(f"Number of GPUs available: {torch.cuda.device_count()}")
print(f"ID of current GPU: {torch.cuda.current_device()}")
print(f"Name of first GPU: {torch.cuda.get_device_name(0)}")
```

**Comment by dharhas** [comment]
We are deploying images with recent GPU's & versions of CUDA drivers (i.e. we dropped k80's) and CUDA is backward compatible so we just need to specify a version greater than 12 and conda should do the right thing. 

```
variables:
  CONDA_OVERRIDE_CUDA: '12.2'
```

cc: @amjames

**Comment by pt247** [comment]
@dharhas Pytorch docs suggest it should be `12.1`
https://pytorch.org/get-started/locally/
<img width="820" alt="pytorch-linux-conda-version" src="https://github.com/nebari-dev/nebari-docs/assets/8033215/b98facbd-6937-4ff6-a78a-d60982938ea4">

Latest draft: [Netlify link](https://deploy-preview-471--nebari-docs.netlify.app/docs/how-tos/use-gpus#building-a-gpu-compatibly-conda-store-environment)

**Comment by dharhas** [comment]
That's fine. We can recommend that folks use that link to determine best version

**Comment by pt247** [comment]
Thanks all for the feedback. Final [Netlify link](https://deploy-preview-471--nebari-docs.netlify.app/docs/how-tos/use-gpus#building-a-gpu-compatibly-conda-store-environment) and [PR](https://github.com/nebari-dev/nebari-docs/pull/471) for review. 
cc. @kcpevey @ericdatakelly
