### ISSUE TITLE
[DOC] Add FAQ item explaining environment naming

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#255]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

**Question:** Why do I see duplication in the names of environments (e.g. the default dask environment named `nebari-git-nebari-git-dask`?

**Answer:**
conda does not recognize the concept of namespaces. Its possible to use conda-store to create and environment with the name `dask` in two different namespaces. But because conda doesn't understand namespaces, conda won't be able to differentiate. To avoid this, we append the namespace into the environment building on conda-store. 

To make things worse the `nb_conda_kernels`  insists the following `/a/path/to/global/datascience-env` -> `global-datascience-env` being the name that users see while `datascience-env` is what conda sees.

So to make things unique we've named things `/a/path/to/global/global-datascience-env` which makes conda see it as `global-datascience-env` but `nb_conda_kernel` now displays it as `global-global-datascience-env`

We could to contribute a PR to `nb_conda_kernels` ... but they haven't accepted a PR in over 3 years so I'm not sure if it'd be merged

### Steps to Resolve this Issue

.

**Comment by viniciusdc** [comment]
All looks correct. As an addition to the above, [`nb_conda_kernels`](https://github.com/Anaconda-Platform/nb_conda_kernels) is the package that we use to transform conda-environment into runnable kernels in jupyterlab (that's why we required that all envs have ipykernel)

For now, a possible direction to fix the above would be:
- work within the inner logic of jupyter or nb_conda_kernels to mask the environment names into something more palatable
- or, add the necessary pattern needed into [nb-conda-store-kernels](https://pypi.org/project/nb-conda-store-kernels/) to avoid depending on nb_conda_kernels
